
async function loadTrades(){const{data,error}=await sb.from('trades').select('*').order('trade_date',{ascending:false});if(error)throw error;trades=data||[]}
function openTrade(){$('#tDate').value=new Date().toISOString().slice(0,10);$('#tradeModal').classList.add('open')}function closeTrade(){$('#tradeModal').classList.remove('open')}
$('#tradeForm').onsubmit=async e=>{e.preventDefault();const risk=+$('#tRisk').value||0,pnl=+$('#tPnl').value||0;const payload={user_id:currentUser.id,trade_date:$('#tDate').value,market:$('#tMarket').value.toUpperCase(),direction:$('#tDirection').value,session:$('#tSession').value,setup:$('#tSetup').value||'Ohne Setup',risk_usd:risk,pnl_usd:pnl,r_multiple:$('#tR').value!==''?+$('#tR').value:(risk?pnl/risk:0),emotion:$('#tEmotion').value,notes:$('#tNotes').value};
if($('#tEntry').value!=='')payload.entry_price=$('#tEntry').value;if($('#tStop').value!=='')payload.stop_loss=$('#tStop').value;if($('#tTp').value!=='')payload.take_profit=$('#tTp').value;
const{error}=await sb.from('trades').insert(payload);if(error)return alert(error.message);e.target.reset();closeTrade();await loadAll();showPage('trading')}
async function deleteTrade(id){if(!confirm('Trade löschen?'))return;await sb.from('trades').delete().eq('id',id);await loadAll()}
function renderTrading(){const w=trades.filter(x=>+x.pnl_usd>0),l=trades.filter(x=>+x.pnl_usd<0),gw=w.reduce((a,x)=>a+(+x.pnl_usd),0),gl=Math.abs(l.reduce((a,x)=>a+(+x.pnl_usd),0)),p=trades.reduce((a,x)=>a+(+x.pnl_usd),0),wr=trades.length?w.length/trades.length*100:0,pf=gl?gw/gl:(gw?Infinity:0),ar=trades.length?trades.reduce((a,x)=>a+(+x.r_multiple||0),0)/trades.length:0;
$('#pnl').textContent=money(p);$('#pnl').className='value '+(p>=0?'pos':'neg');$('#winrate').textContent=wr.toFixed(1)+'%';$('#profitFactor').textContent=pf===Infinity?'∞':pf.toFixed(2);$('#tradeCount').textContent=trades.length;$('#tpnl').textContent=money(p);$('#tpnl').className='value '+(p>=0?'pos':'neg');$('#twinrate').textContent=wr.toFixed(1)+'%';$('#tavgR').textContent=ar.toFixed(2)+'R';$('#tcount').textContent=trades.length;
$('#tradeRows').innerHTML=trades.map(t=>`<tr><td>${t.trade_date}</td><td><b>${t.market}</b></td><td><span class="badge ${t.direction.toLowerCase()}">${t.direction}</span></td><td>${t.session||'-'}</td><td>${t.setup||'-'}</td><td class="${+t.pnl_usd>=0?'pos':'neg'}"><b>${money(t.pnl_usd)}</b></td><td>${(+t.r_multiple||0).toFixed(2)}R</td><td><button class="btn danger" onclick="deleteTrade('${t.id}')">Löschen</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">Noch keine Trades.</td></tr>'}
